### ISSUE TITLE
Need JS for Interactivity

### ISSUE THREAD

**Issue by chandrakantbk** [chandrakantbk/shopping-portal#3]
Please create JS/shared.db.js and write a function named _show_welcome_message_

function show_welcome_message( ){

}

**Comment by chandrakantbk** [comment]
@chandrakantbk Please check I have the the issue

**Comment by namratajain103** [comment]
@chandrakantbk JS file added in project. @kanchan-shinde kindly solve your issue.

**Comment by chandrakantbk** [comment]
@kanchan-shinde please let me know once you fix the issue.
